package com.zhan.memoryservice.tracker;

import com.zhan.memoryservice.model.TokenUsage;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.stereotype.Service;

import java.time.Instant;
import java.util.List;

/**
 * Token 用量追踪器 — 记录每次 LLM/Embedding 调用的 token 消耗到 H2，
 * 并汇总按模型统计，供前端展示。
 */
@Service
@ConditionalOnProperty(prefix = "memory-service.postgres", name = "enabled", havingValue = "true")
public class TokenUsageTracker {

    private static final Logger log = LoggerFactory.getLogger(TokenUsageTracker.class);

    private final JdbcClient jdbcClient;
    private final boolean noop;

    public TokenUsageTracker(JdbcClient jdbcClient) {
        this.jdbcClient = jdbcClient;
        this.noop = false;
        initTable();
    }

    private TokenUsageTracker() {
        this.jdbcClient = null;
        this.noop = true;
        log.warn("TokenUsageTracker 使用 noop 模式，token 用量不会持久化");
    }

    public static TokenUsageTracker noop() {
        return new TokenUsageTracker();
    }

    private void initTable() {
        jdbcClient.sql("""
            CREATE TABLE IF NOT EXISTS token_usage (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                call_type VARCHAR(20) NOT NULL,
                model VARCHAR(100) NOT NULL,
                prompt_tokens INT NOT NULL DEFAULT 0,
                completion_tokens INT NOT NULL DEFAULT 0,
                total_tokens INT NOT NULL DEFAULT 0,
                created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
            )
            """).update();
    }

    /** 记录一次调用 */
    public void record(TokenUsage usage) {
        if (noop) {
            log.debug("Token usage skipped in noop mode: [{}] {}", usage.callType(), usage.model());
            return;
        }
        jdbcClient.sql("""
            INSERT INTO token_usage (call_type, model, prompt_tokens, completion_tokens, total_tokens, created_at)
            VALUES (:callType, :model, :promptTokens, :completionTokens, :totalTokens, :createdAt)
            """)
            .param("callType", usage.callType())
            .param("model", usage.model())
            .param("promptTokens", usage.promptTokens())
            .param("completionTokens", usage.completionTokens())
            .param("totalTokens", usage.totalTokens())
            .param("createdAt", usage.createdAt())
            .update();

        log.info("Token used: [{}] {} — prompt={}, completion={}, total={}",
                usage.callType(), usage.model(),
                usage.promptTokens(), usage.completionTokens(), usage.totalTokens());
    }

    /** 按模型汇总总量（供前端仪表盘） */
    public List<TokenSummary> summaries() {
        if (noop) {
            return List.of();
        }
        return jdbcClient.sql("""
            SELECT model, call_type, SUM(total_tokens) AS total
            FROM token_usage
            GROUP BY model, call_type
            ORDER BY total DESC
            """)
            .query(TokenSummary.class)
            .list();
    }

    /** 按日期汇总（7 天内的每日消耗） */
    public List<DailySummary> dailySummaries(int days) {
        if (noop) {
            return List.of();
        }
        return jdbcClient.sql("""
            SELECT CAST(created_at AS DATE) AS date, SUM(total_tokens) AS total
            FROM token_usage
            WHERE created_at >= CURRENT_DATE - :days
            GROUP BY CAST(created_at AS DATE)
            ORDER BY date
            """)
            .param("days", days)
            .query(DailySummary.class)
            .list();
    }

    /** 模型维度汇总 */
    public record TokenSummary(String model, String callType, long total) {}

    /** 日期维度汇总 */
    public record DailySummary(String date, long total) {}
}
